#Database info for DEV
spring:
 datasource:
  driver-class-name: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@localhost:1521/xe
  username: dev
  password: dev
  db-name : Development Database
